<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Bundle\Block\Sales\Order\Items\Renderer */ ?>

<?php
$parentItem = $block->getItem();
$type = $block->getType();
$items = $block->getChildren($parentItem);
$_index = 0;
$_order = $block->getOrder();
$block->setStoreId($_order->getStoreId());
$isBarcode = $block->getIsBarcode();
?>

<?php if ($block->getItemOptions() || $parentItem->getDescription() || $this->helper('Magento\GiftMessage\Helper\Message')->isMessagesAllowed('order_item', $parentItem) && $parentItem->getGiftMessageId()): ?>
    <?php $_showlastRow = true ?>
<?php else: ?>
    <?php $_showlastRow = false ?>
<?php endif ?>

<?php $i = 0 ?>
<?php $_prevOptionId = '' ?>
<?php foreach ($items as $_item): ?>
    <?php
    // As part of invoice item renderer logic, the order is set on each invoice item.
    // In the case of a bundle product, this template takes over rendering its children,
    // so it is necessary to pass the order along to each child.
    $_item->setOrder($_order);
    $i++;
    ?>
    <tr class="mp-row bundle-item <?= /** @noEscape */ $block->getIndexKey() ?>">
        <?php if (!$_item->getOrderItem()->getParentItem()): ?>
            <td class="mp-netamt">
                <?= /* @noEscape */ $_order->formatPrice($_item->getRowTotalInclTax()) ?>
            </td>
            <td class="mp-vatamt">
                <?= /* @noEscape */ $_order->formatPrice($_item->getTaxAmount()) ?>
            </td>
            <td class="mp-disamt">
                <?= /* @noEscape */ $_order->formatPrice($_item->getDiscountAmount()) ?>
            </td>
            <td class="mp-subtotal">
                <?= /* @noEscape */ $_order->formatPrice($_item->getRowTotal()) ?>
            </td>
            <td class="mp-price">
                <?= /* @noEscape */
                    $_order->formatPrice($_item->getPrice()) ?>
            </td>
            <td class="mp-qty">
                <span><?= /* @noEscape */
                    $_item->getQty() * 1 ?></span>
            </td>
            <td class="mp-item">
                <p class="product-name"><?= $block->escapeHtml($_item->getName()) ?></p>
            </td>
            <td class="mp-code">
                <p class="sku"><?= $block->escapeHtml($block->getSku($_item)) ?></p>
            </td>
            <td class="mp-ln"><?= $i ?></td>
        <?php else: ?>
            <td class="mp-netamt"></td>
            <td class="mp-vatamt"></td>
            <td class="mp-disamt"></td>
            <td class="mp-subtotal"></td>
            <td class="mp-price">
                <?= /* @noEscape */
                    $_order->formatPrice($_item->getPrice()) ?>
            </td>
            <td class="mp-qty">
                <span><?= /* @noEscape */
                    $_item->getQty() * 1 ?></span>
            </td>
            <td class="mp-item">
                <p class="product-name"><?= $block->escapeHtml($_item->getName()) ?></p>
            </td>
            <td class="mp-code">
                <p class="sku"><?= $block->escapeHtml($_item->getSku()) ?></p>
            </td>
            <td class="mp-ln"><?= $i ?></td>
        <?php endif ?>
    </tr>
<?php endforeach ?>

<?php if ($_showlastRow): ?>
    <tr class="mp-row">
        <td class="item-extra" colspan="9">
            <?php if ($block->getItemOptions()): ?>
                <div>
                    <?php foreach ($block->getItemOptions() as $option): ?>
                        <div><strong><em><?= /* @noEscape */
                                    $option['label'] ?></em></strong></div>
                        <div><?= /* @noEscape */
                            $option['value'] ?></div>
                    <?php endforeach ?>
                </div>
            <?php endif ?>
            <?= $block->escapeHtml($_item->getDescription()) ?>
        </td>
    </tr>
<?php endif ?>
<div class="clr"></div>

